---
- name: Test DB 
  hosts: hammer
  become: true
  tasks:
    - name: Change to HammerDB directory
      command: chdir=HammerDB-4.1
               cmd=./hammerdbcli
      ignore_errors: true

    - name: run Test
      command: chdir=HammerDB-4.1
                cmd=./hammerdbcli -t "dbset db pg; dbset bm tpc-c; diset connection pg_host {{ hammer_ip }}; diset tpcc pg_count_ware 20; diset tpcc pg_superuserpass admin; diset tpcc pg_total_iterations 10000000; diset tpcc pg_rampup 5; diset tpcc pg_duration 15; diset tpcc pg_driver timed; loadscript; vuset vu 3; vuset vu logtotemp 1; vucreate; vurun; vudestroy"
      ignore_errors: true
      register: test_op

    - name: Display test op 
      debug:
        var: test_op
